# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod properties
mod.name=GlintColorizer
mod.id=glintcolorizer
mod.version=1.0
mod.group=btw.lowercase.glintcolorizer
mod.description=Customize the glint of enchanted items.
mod.source=https://github.com/lowercasebtw/GlintColorizerModern
mod.issues=https://github.com/lowercasebtw/GlintColorizerModern/issues
mod.license=GPL-3.0

# Dependencies
deps.fabric_loader_version=0.17.3
deps.oneconfig_version=1.0.0-alpha.181

# Build Plugins
# in libs.versions.toml

# Minecraft properties
mod.minecraft_version=[VERSIONED]
mod.minecraft_version_range=[VERSIONED]

# Versioned
deps.parchment_version=[VERSIONED]
deps.fabric_api_version=[VERSIONED]